spring.application.name=vynk
spring.config.import=optional:file:.env[.properties]
spring.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/vynk}

vynk.auth.issuer=${OAUTH_ISSUER}
vynk.auth.jwks-uri=${OAUTH_JWKS_URI}
vynk.auth.client-id=${OAUTH_CLIENT_ID}
vynk.auth.dominio=@tecsup.edu.pe
vynk.jwt.secret=${JWT_SECRET}
vynk.jwt.horas=8
server.port=8081